### PR TITLE
Primitive types

### PR DESCRIPTION
**Pull request by jeffsee55**
👀 [Read about the changes](https://github.com/tinacms/tina-graphql-gateway/blob/primitive-types-4/.changeset/perfect-houses-turn.md)

### CODE REVIEW

**Comment by logan-anderson** [comment]
Getting this error when reloading the dev server

```
.tina/schema.ts not found or is malformed, please create this file and commit it to Github. Documentation; https://tina.io/docs/tina-cloud/cli/#getting-started
```

**Comment by jeffsee55** [comment]
> Getting this error when reloading the dev server

This should be fixed now

**Comment by logan-anderson** [comment]
Deleting all of the `/dist` folders and running `yarn build` yields
```
yarn build 
➤ YN0000:  CLI  Using tsconfig: /Users/logananderson-forestry-mac/dev/tinacms/tina-graphql-gateway/packages/tina-cloud-next/tsconfig.json
➤ YN0000:  CLI  Target: es2017
➤ YN0000:  CJS  Build start
➤ YN0000:  CJS  Build success in 4ms
➤ YN0000:  DTS  Build start
➤ YN0000:  DTS  Build success in 1662ms
➤ YN0000:  CLI  Using tsconfig: /Users/logananderson-forestry-mac/dev/tinacms/tina-graphql-gateway/packages/tina-graphql-helpers/tsconfig.json
➤ YN0000:  CLI  Target: es2017
➤ YN0000:  CJS  Build start
➤ YN0000:  CJS  Build success in 7ms
➤ YN0000:  DTS  Build start
➤ YN0000:  DTS  Build success in 1964ms
➤ YN0000: MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 uncaughtException listeners added to [process]. Use emitter.setMaxListeners() to increase limit
➤ YN0000:  CLI  Using tsconfig: /Users/logananderson-forestry-mac/dev/tinacms/tina-graphql-gateway/packages/tina-graphql-gateway/tsconfig.json
➤ YN0000:  CLI  Target: es2017
➤ YN0000:  CJS  Build start
➤ YN0000:  CJS  Build success in 11ms
➤ YN0000:  DTS  Build start
➤ YN0000:  DTS  Build success in 3328ms
➤ YN0000:  CLI  Using tsconfig: /Users/logananderson-forestry-mac/dev/tinacms/tina-graphql-gateway/packages/tina-graphql/tsconfig.json
➤ YN0000:  CLI  Target: es2017
➤ YN0000:  CJS  Build start
➤ YN0000:  CJS  Build success in 22ms
➤ YN0000:  DTS  Build start
➤ YN0000:  DTS  Build success in 8549ms
➤ YN0000:  CLI  Using tsconfig: /Users/logananderson-forestry-mac/dev/tinacms/tina-graphql-gateway/packages/next-tinacms-cloudinary/tsconfig.json
➤ YN0000:  CLI  Target: es2017
➤ YN0000:  CJS  Build start
➤ YN0000:  CJS  Build success in 6ms
➤ YN0000:  DTS  Build start
➤ YN0000:  DTS  Build success in 2221ms
➤ YN0000:  CLI  Building entry: src/index.ts
➤ YN0000:  CLI  Using tsconfig: /Users/logananderson-forestry-mac/dev/tinacms/tina-graphql-gateway/packages/tina-graphql-gateway-cli/tsconfig.json
➤ YN0000:  CLI  Target: es2017
➤ YN0000:  CJS  Build start
➤ YN0000:  CJS  Build success in 38ms
➤ YN0000:  DTS  Build start
➤ YN0000:  DTS  Build error
➤ YN0000: src/cmds/compile/index.ts(369,11): error TS2314: Generic type 'TinaCloudSchema<WithNamespace>' requires 1 type argument(s).
➤ YN0000: 
➤ YN0000: Error: Could not load /Users/logananderson-forestry-mac/dev/tinacms/tina-graphql-gateway/packages/tina-graphql-gateway-cli/src/cmds/compile/index.ts (imported by src/index.ts): Failed to compile. Check the logs above.
➤ YN0000:     at error (/Users/logananderson-forestry-mac/dev/tinacms/tina-graphql-gateway/.yarn/cache/rollup-npm-2.40.0-f6c7b660f3-c512236087.zip/node_modules/rollup/dist/shared/rollup.js:5279:30)
➤ YN0000:     at throwPluginError (/Users/logananderson-forestry-mac/dev/tinacms/tina-graphql-gateway/.yarn/cache/rollup-npm-2.40.0-f6c7b660f3-c512236087.zip/node_modules/rollup/dist/shared/rollup.js:18240:12)
➤ YN0000:     at Object.error (/Users/logananderson-forestry-mac/dev/tinacms/tina-graphql-gateway/.yarn/cache/rollup-npm-2.40.0-f6c7b660f3-c512236087.zip/node_modules/rollup/dist/shared/rollup.js:18847:24)
➤ YN0000:     at Object.load (/Users/logananderson-forestry-mac/dev/tinacms/tina-graphql-gateway/.yarn/$$virtual/tsup-virtual-cada2ee815/0/cache/tsup-npm-4.6.1-ec1883c0f6-a86da36251.zip/node_modules/tsup/dist/rollup.js:1756:18)
➤ YN0000:     at /Users/logananderson-forestry-mac/dev/tinacms/tina-graphql-gateway/.yarn/cache/rollup-npm-2.40.0-f6c7b660f3-c512236087.zip/node_modules/rollup/dist/shared/rollup.js:19049:25
➤ YN0000: The command failed for workspaces that are depended upon by other workspaces; can't satisfy the dependency graph
➤ YN0000: Failed with errors in 22s 1ms
```

**Comment by jeffsee55** [comment]
Thanks @logan-anderson , I just tried to update those yesterday - your fix is the correct change

**Pull request closed without merging**
