### PR TITLE
Cli updates

### PR DESCRIPTION
**Pull request by logan-anderson**
New output of init command
Fixes https://github.com/tinacms/tina-graphql-gateway/issues/288
```
Sit back and relax while we set up Tina for you…
Installing dependencies...
✅ Installed Tina Dependencies
Setting up Tina...
Adding a content folder...
✅ Setup your first post in /Users/logananderson-forestry-mac/dev/tinacms/tina-graphql-gateway/apps/tmp/content/posts/HelloWorld.md
✅ Setup a blog page in /Users/logananderson-forestry-mac/dev/tinacms/tina-graphql-gateway/apps/tmp/pages/demo/blog/[filename].tsx

Tina Cloud is now properly setup, just a couple of things before you get started
        1. please add the following scripts to your package.json
"dev": "yarn tina-gql server:start -c \"next dev\"",
"build": "yarn tina-gql server:start -c \"next build\"",
"start": "yarn tina-gql server:start -c \"next start\""
```

@mitchmac Does anything else need to be removed?

### CODE REVIEW

**Comment by DirtyF** [comment]
An alternative version:

```
Setting up Tina...
Installing dependencies... ✅
Adding a content folder... ✅
Tina setup  ✅

Before you get started:

1. Add the following scripts to your package.json:
"dev": "yarn tina-gql server:start -c \"next dev\"",
"build": "yarn tina-gql server:start -c \"next build\"",
"start": "yarn tina-gql server:start -c \"next start\"" 

2. Check the page and the post created at:
 /Users/logananderson-forestry-mac/dev/tinacms/tina-graphql-gateway/apps/tmp/pages/demo/blog/[filename].tsx
/Users/logananderson-forestry-mac/dev/tinacms/tina-graphql-gateway/apps/tmp/content/posts/HelloWorld.md

Enjoy Tina!
```

**Comment by logan-anderson** [comment]
@jeffsee55  is there anyway we could do a canary release so we can start doing some user testing? or should we just merge this ?

**Comment by jeffsee55** [comment]
Feel free to do a canary, I've outline the steps here https://github.com/tinacms/tina-graphql-gateway/blob/main/CONTRIBUTING.md#creating-a-beta-release...

having said that I don't care either way, we haven't announced this feature publicly

**Comment by logan-anderson** [comment]
I think merging it is fine for now

**Review by Enigmatical — APPROVED** [review]
Looks good to me 👍

**Pull request merged**
